"""Domain models package for Before You Pay."""

from before_you_pay.models.analysis import (
    AnalysisState,
    ClaimType,
    DecisionFlag,
    DecisionStatus,
    FinalDecisionSupportResult,
    OCRQualityResult,
    OCRQualityStatus,
    OkfCategory,
    OkfQuery,
    OkfRuleEvidence,
    PlainLanguageExplanation,
    PotentialCostReductionSummary,
    RagEvidenceChunk,
    RagQuery,
    ReasoningClaim,
    ReductionTierItem,
    ResultSummary,
    SmartCostReductionQuestion,
    StandardError,
    ValidationCheck,
    ValidationSeverity,
    ValidationStatus,
)
from before_you_pay.models.cost_review import (
    CostReviewClassification,
    CostReviewQuestion,
)
from before_you_pay.models.document import (
    BoundingBox,
    ChargeNature,
    ComponentCategory,
    CoordinateUnit,
    DocumentClassification,
    DocumentMetadata,
    ExtractedField,
    FieldProvenance,
    FinancialComponent,
    LineItem,
    OcrLine,
    OcrPage,
    OcrResult,
    OptionalityStatus,
    StructuredFinancialDocument,
)

__all__ = [
    # Document & Extraction
    "BoundingBox",
    "CoordinateUnit",
    "DocumentClassification",
    "ComponentCategory",
    "ChargeNature",
    "OptionalityStatus",
    "DocumentMetadata",
    "OcrLine",
    "OcrPage",
    "OcrResult",
    "FieldProvenance",
    "ExtractedField",
    "LineItem",
    "FinancialComponent",
    "StructuredFinancialDocument",
    # Analysis & Results
    "AnalysisState",
    "OCRQualityStatus",
    "OCRQualityResult",
    "StandardError",
    "ValidationStatus",
    "ValidationSeverity",
    "ClaimType",
    "DecisionStatus",
    "DecisionFlag",
    "ResultSummary",
    "FinalDecisionSupportResult",
    "RagEvidenceChunk",
    "RagQuery",
    "OkfCategory",
    "OkfRuleEvidence",
    "OkfQuery",
    "ValidationCheck",
    "ReasoningClaim",
    "SmartCostReductionQuestion",
    "CostReviewClassification",
    "CostReviewQuestion",
    "ReductionTierItem",
    "PotentialCostReductionSummary",
    "PlainLanguageExplanation",
]
